# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Liyi/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-15160-DESKTOP-6KORK05/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Codes/Verilog/Lab3_Lab4_CPU/Lab3_CPU2.cache/wt [current_project]
set_property parent.project_path D:/Codes/Verilog/Lab3_Lab4_CPU/Lab3_CPU2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Codes/Verilog/Lab3_Lab4_CPU/Lab3_CPU2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Codes/Verilog/vsrc/test.coe
add_files D:/Codes/Verilog/Lab3_Lab4_CPU/text1.coe
add_files D:/Codes/Verilog/Lab3_Lab4_CPU/text2.coe
add_files D:/Codes/Verilog/Lab3_Lab4_CPU/text1-2.coe
add_files D:/Codes/Verilog/Lab3_Lab4_CPU/text2-2.coe
add_files D:/Codes/Verilog/Lab3_Lab4_CPU/fabo.coe
add_files D:/Codes/Verilog/lab5_test1.coe
add_files D:/Codes/Verilog/lab5_test2.coe
add_files D:/Codes/Verilog/lab6.coe
add_files D:/Codes/Verilog/te.coe
add_files D:/Codes/Verilog/t.coe
add_files D:/Codes/Verilog/data.coe
read_verilog -library xil_defaultlib {
  D:/Codes/Verilog/vsrc/PDU/RTL/BP_LIST_REG.v
  D:/Codes/Verilog/vsrc/CPU/include/config.v
  D:/Codes/Verilog/vsrc/CPU/CPU.v
  D:/Codes/Verilog/vsrc/PDU/UTILS/HEX2ASCII.v
  D:/Codes/Verilog/vsrc/PDU/UTILS/HEX2UART.v
  D:/Codes/Verilog/vsrc/PDU/RTL/INFO_SENDER.v
  D:/Codes/Verilog/vsrc/MEM/MEM_BRIDGE.v
  D:/Codes/Verilog/vsrc/MEM/MMIO.v
  D:/Codes/Verilog/vsrc/PDU/PDU.v
  D:/Codes/Verilog/vsrc/PDU/RTL/PDU_decode.v
  D:/Codes/Verilog/vsrc/PDU/UTILS/POSEDGE_GEN.v
  D:/Codes/Verilog/vsrc/PDU/UTILS/QUEUE.v
  D:/Codes/Verilog/vsrc/PDU/UTILS/Segment.v
  D:/Codes/Verilog/vsrc/PDU/UART/UART_RX.v
  D:/Codes/Verilog/vsrc/PDU/UART/UART_TX.v
  D:/Codes/Verilog/vsrc/TOP.v
}
read_ip -quiet D:/Codes/Verilog/Lab3_Lab4_CPU/Lab3_CPU2.srcs/sources_1/ip/DATA_MEM/DATA_MEM.xci
set_property used_in_implementation false [get_files -all d:/Codes/Verilog/Lab3_Lab4_CPU/Lab3_CPU2.srcs/sources_1/ip/DATA_MEM/DATA_MEM_ooc.xdc]

read_ip -quiet D:/Codes/Verilog/Lab3_Lab4_CPU/Lab3_CPU2.srcs/sources_1/ip/INST_MEM/INST_MEM.xci
set_property used_in_implementation false [get_files -all d:/Codes/Verilog/Lab3_Lab4_CPU/Lab3_CPU2.srcs/sources_1/ip/INST_MEM/INST_MEM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Codes/Verilog/vsrc/constraints.xdc
set_property used_in_implementation false [get_files D:/Codes/Verilog/vsrc/constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top TOP -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
